### ISSUE TITLE
trace propagation for grpc

### ISSUE THREAD

**Issue by xd009642** [jtescher/opentelemetry-rust#17]
I see that there's no alpha date for this, but there is already basic HTTP trace propagation. I was wondering if there was any way someone else could help contribute to this and if there are any blockers?

**Comment by jtescher** [comment]
This is definitely something that would be great to see and a good opportunity to contribute! @davidbarsky was bringing up the option of using https://github.com/hyperium/tonic

**Comment by xd009642** [comment]
So I'm actually using tonic as my grpc implementation so that's something I'd definitely be up for.

I'll have a look at the tonic source and see if I can figure it out but I'll probably need some more guidance. If so I'll likely ask in the tokio discord channel :+1:

**Comment by davidbarsky** [comment]
@jtescher I apologize for not being as clear as I should have been: I was thinking that tonic could be used to communicate _directly_ to Jaeger over its gRPC API instead of the current mechanism. That said, I'm not sure if that's valuable work at this time 😄.

**Comment by xd009642** [comment]
@davidbarsky I still think it would be useful to provide span propagation in the Server Builder for `tonic::transport::Server` (and the relevant client methods) I'll open an issue in tonic for it to discuss though :)

**Comment by jtescher** [comment]
@davidbarsky ah right!

**Comment by davidbarsky** [comment]
@xd009642 No disagreement there!

**Comment by xd009642** [comment]
https://github.com/hyperium/tonic/issues/156 I've just made the issue and included a bit of a bonus implementation a friend and me worked on :+1:
